### ISSUE TITLE
More Structures

### ISSUE THREAD

**Issue by riesters** [wode490390/ScatteredBuildingPopulator#1]
Hi can you please add Stronghold, Ocean Monument, Woodland Mansion, and Nether Fortresses?

**Comment by wode490390** [comment]
- Stronghold: https://github.com/wode490390/StrongholdPopulator
- Ocean Monument: https://github.com/wode490390/OceanMonumentPopulator
- Woodland Mansion: WIP
- Nether Fortress: https://github.com/wode490390/NetherFortressPopulator

**Comment by riesters** [comment]
Any eta for woodland mansion plugin?
